language: php

dist: trusty
sudo: false

cache:
  directories:
    - vendor

matrix:
  include:
    - php: 5.6
      env: LEAGUE_VERSION=5.1.*  JWT_VERSION=3.4.*
    - php: 5.6
      env: LEAGUE_VERSION=6.0.*  JWT_VERSION=3.4.*
    - php: 5.6
      env: LEAGUE_VERSION=6.1.*  JWT_VERSION=3.4.*

    - php: 7.0
      env: LEAGUE_VERSION=5.1.*  JWT_VERSION=3.4.*
    - php: 7.0
      env: LEAGUE_VERSION=6.0.*  JWT_VERSION=3.4.*
    - php: 7.0
      env: LEAGUE_VERSION=6.1.*  JWT_VERSION=3.4.*
    - php: 7.0
      env: LEAGUE_VERSION=7.0.*  JWT_VERSION=3.4.*

    - php: 7.1
      env: LEAGUE_VERSION=5.1.*  JWT_VERSION=3.4.*
    - php: 7.1
      env: LEAGUE_VERSION=6.0.*  JWT_VERSION=3.4.*
    - php: 7.1
      env: LEAGUE_VERSION=6.1.*  JWT_VERSION=3.4.*
    - php: 7.1
      env: LEAGUE_VERSION=7.0.*  JWT_VERSION=3.4.*
    - php: 7.1
      env: LEAGUE_VERSION=8.0.*  JWT_VERSION=3.4.*

    - php: 7.2
      env: LEAGUE_VERSION=5.1.*  JWT_VERSION=3.4.*
    - php: 7.2
      env: LEAGUE_VERSION=6.0.*  JWT_VERSION=3.4.*
    - php: 7.2
      env: LEAGUE_VERSION=6.1.*  JWT_VERSION=3.4.*
    - php: 7.2
      env: LEAGUE_VERSION=7.0.*  JWT_VERSION=3.4.*
    - php: 7.2
      env: LEAGUE_VERSION=8.0.*  JWT_VERSION=3.4.*

    - php: 7.3
      env: LEAGUE_VERSION=8.0.*  JWT_VERSION=3.4.*

    - php: 7.4
      env: LEAGUE_VERSION=8.0.*  JWT_VERSION=3.4.*
    - php: 7.4
      env: LEAGUE_VERSION=8.0.*  JWT_VERSION=^4

    - php: 8.0
      env: LEAGUE_VERSION=8.0.*  JWT_VERSION=4.1.*

before_install:
  - composer require league/oauth2-server:$LEAGUE_VERSION --prefer-source --no-update
  - composer require lcobucci/jwt:$JWT_VERSION --prefer-source --no-update
  - chmod 600 $TRAVIS_BUILD_DIR/tests/Stubs/private.key
  - chmod 600 $TRAVIS_BUILD_DIR/tests/Stubs/public.key

install:
  - composer update --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - master
    - develop
