language: php

dist: trusty
sudo: false

cache:
  directories:
    - vendor

env:
  - LEAGUE_VERSION=5.1.*

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 5.6
      env: LEAGUE_VERSION=5.1.*
    - php: 5.6
      env: LEAGUE_VERSION=6.0.*
    - php: 5.6
      env: LEAGUE_VERSION=6.1.*
    - php: 7.0
      env: LEAGUE_VERSION=5.1.*
    - php: 7.0
      env: LEAGUE_VERSION=6.0.*
    - php: 7.0
      env: LEAGUE_VERSION=6.1.*
    - php: 7.0
      env: LEAGUE_VERSION=7.0.*
    - php: 7.1
      env: LEAGUE_VERSION=5.1.*
    - php: 7.1
      env: LEAGUE_VERSION=6.0.*
    - php: 7.1
      env: LEAGUE_VERSION=6.1.*
    - php: 7.1
      env: LEAGUE_VERSION=7.0.*
    - php: 7.2
      env: LEAGUE_VERSION=5.1.*
    - php: 7.2
      env: LEAGUE_VERSION=6.0.*
    - php: 7.2
      env: LEAGUE_VERSION=6.1.*
    - php: 7.2
      env: LEAGUE_VERSION=7.0.*

before_install:
  - composer require league/oauth2-server:$LEAGUE_VERSION --prefer-source --no-update
  - chmod 600 $TRAVIS_BUILD_DIR/tests/Stubs/private.key
  - chmod 600 $TRAVIS_BUILD_DIR/tests/Stubs/public.key

install:
  - composer update --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - master
    - develop
